version: "3.8"

services:
  kaggle:
    build: .
    volumes:
      - ./:/workspace
      - ./notebook:/workspace/notebook
      - ./src:/workspace/src
      - ./conf:/workspace/conf
      - ./input:/workspace/input
      - ./output:/workspace/output
      - ./.jupyter:/root/.jupyter 
    working_dir: 
    environment:
      - JUPYTERLAB_SETTINGS_DIR=/kaggle/working/.jupyter-settings # jupyterの設定(保存用)
    ports:
      - 8889:8889
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8889 --no-browser --NotebookApp.token=''
    shm_size: '8gb'
